export const gamesData = [
  { title: { en: "99 Balls" }, img: "ninety-nine-balls", url: "/ninety-nine-balls/", genre: "puzzle" },
  { title: { en: "Angry Birds" }, img: "angry-birds", url: "/angrybirds.htm", genre: "action" },
  { title: { en: "Basket Random" }, img: "basket-random", url: "/randoms/basket/", genre: "sports" },
  { title: { en: "Battle Racing Stars" }, img: "battle-racing-stars", url: "/battle-racing-stars/", genre: "racing", broken: true },
  { title: { en: "BitLife" }, img: "bitlife", url: "/bitlife/", genre: "adventure", popular: true },
  { title: { en: "Block Blast" }, img: "block-blast", url: "/block-blast/", genre: "puzzle" },
  { title: { en: "Bloons Tower Defence 5" }, img: "btd5", url: "/btd5.htm", genre: "action" },
  { title: { en: "Boxing Random" }, img: "boxing-random", url: "/randoms/boxing/", genre: "sports" },
  { title: { en: "Breaking the Bank" }, img: "breaking-the-bank", url: "/stickmin/breakingthebank/", genre: "puzzle" },
  { title: { en: "Bridge Race" }, img: "bridge-race", url: "/bridge-race/", genre: "survival" },
  { title: { en: "Car Drawing Game" }, img: "car-drawing-game", url: "/car-drawing-game/", genre: "racing" },
  { title: { en: "Cookie Clicker" }, img: "cookie-clicker", url: "/cookieclicker/", genre: "clicker", broken: true, issue: '59' },
  { title: { en: "Crazy Crash Landing" }, img: "crazy-crash-landing", url: "/ccl.htm", genre: "survival" },
  { title: { en: "Crossy Road" }, img: "crossy-road", url: "/crossy-road.html", genre: "racing" },
  { title: { en: "Cut the Rope" }, img: "ctr", url: "/ctr/", genre: "puzzle" },
  { title: { en: "Cut The Rope: Time Travel" }, img: "ctr-time-travel", url: "/time-travel/index.html", genre: "puzzle" },
  { title: { en: "Darts Pro" }, img: "darts-pro", url: "/dartspro/", genre: "sports" },
  { title: { en: "Doge Miner" }, img: "doge-miner", url: "/DogeMiner/", genre: "clicker" },
  { title: { en: "Doge Miner 2" }, img: "doge-miner-2", url: "/doge-miner-2/", genre: "clicker" },
  { title: { en: "Draw Climber" }, img: "draw-climber", url: "/draw-climber/", genre: "puzzle" },
  { title: { en: "Draw the Hill" }, img: "draw-the-hill", url: "/draw-the-hill/", genre: "puzzle" },
  { title: { en: "Drift Boss" }, img: "drift-boss", url: "/drift-boss/", genre: "racing" },
  { title: { en: "Drive Mad" }, img: "drive-mad", url: "/drive-mad/", genre: "racing", popular: true },
  { title: { en: "Driven Wild" }, img: "driven-wild", url: "/drivenwild/index.html", genre: "racing" },
  { title: { en: "Duck Duck Clicker" }, img: "duck-duck-clicker", url: "/duck-duck-clicker/", genre: "clicker" },
  { title: { en: "Escaping the Prison" }, img: "escaping-the-prison", url: "/stickmin/escapingtheprison/", genre: "puzzle" },
  { title: { en: "Fast Runner" }, img: "fast-runner", url: "/fast-runner/", genre: "racing" },
  { title: { en: "Five Nights at Epstein's" }, img: "fnae", url: "/fnae.html", genre: "survival", horror: true },
  { title: { en: "Five Nights at Freddy's 1" }, img: "fnaf-1", url: "/fnaf/FNAF1/", genre: "survival", horror: true },
  { title: { en: "Five Nights at Freddy's 2" }, img: "fnaf-2", url: "/fnaf/FNAF2/", genre: "survival", horror: true, broken: true },
  { title: { en: "Five Nights at Freddy's 3" }, img: "fnaf-3", url: "/fnaf/FNAF3/", genre: "survival", horror: true },
  { title: { en: "Flappy Bird" }, img: "flappy-bird", url: "/flappy-bird/", genre: "survival" },
  { title: { en: "Fleeing the Complex" }, img: "fleeing-the-complex", url: "/stickmin/fleeingthecomplex/", genre: "puzzle" },
  { title: { en: "Formula Rush" }, img: "formula-rush", url: "/formula-rush/", genre: "racing" },
  { title: { en: "Fruit Ninja" }, img: "fruit-ninja", url: "/fruitninja.htm", genre: "puzzle" },
  { title: { en: "Geometry Dash SubZero" }, img: "gd-subzero", url: "/gd-sub0.htm", genre: "survival" },
  { title: { en: "Geometry Dash Wave" }, img: "gd-wave", url: "/gd-wave/", genre: "survival" },
  { title: { en: "Geometry Dash World" }, img: "gd-world", url: "/gdworld.htm", genre: "survival" },
  { title: { en: "Gobble" }, img: "gobble", url: "/gobble/", genre: "action" },
  { title: { en: "Google Games Baseball" }, img: "gg-baseball", url: "/baseball/", genre: "sports" },
  { title: { en: "Google Games Cricket" }, img: "gg-cricket", url: "/cricket17/", genre: "sports" },
  { title: { en: "GunSpin" }, img: "gunspin", url: "/gunspin/", genre: "action", popular: true },
  { title: { en: "Happy Glass" }, img: "happy-glass", url: "/happyglass/", genre: "puzzle" },
  { title: { en: "Hundred Percent Golf" }, img: "hundred-percent-golf", url: "/hundred-percent-golf/index.html", genre: "sports", broken: true },
  { title: { en: "Idle Football Manager" }, img: "idle-football-manager", url: "/idle-football/", genre: "sports" },
  { title: { en: "Impossible Quiz" }, img: "impossible-quiz", url: "/impossiblequiz/", genre: "puzzle" },
  { title: { en: "Infiltrating the Airship" }, img: "infiltrating-the-airship", url: "/stickmin/infiltratingtheairship/", genre: "puzzle" },
  { title: { en: "Jetpack Joyride" }, img: "jetpack-joyride", url: "/jetpack-joyride/", genre: "action" },
  { title: { en: "Knife Hit" }, img: "knife-hit", url: "/knifehit/", genre: "puzzle" },
  { title: { en: "Liquid Sort" }, img: "liquid-sort", url: "/liquid-sort/", genre: "puzzle" },
  { title: { en: "Monkey Mart" }, img: "monkey-mart", url: "/monkey-mart.html", genre: "adventure" },
  { title: { en: "Monster Tracks" }, img: "monster-tracks", url: "/monster-tracks.html", genre: "racing" },
  { title: { en: "Moto X3M" }, img: "moto-x3m", url: "/moto-x3m.html", genre: "racing" },
  { title: { en: "Moto X3M Winter" }, img: "moto-x3m-winter", url: "/x3m/", genre: "racing" },
  { title: { en: "No Pain, No Gain" }, img: "no-pain-no-gain", url: "/npng/", genre: "action", popular: true },
  { title: { en: "Nut Sort" }, img: "nut-sort", url: "/nutsort/", genre: "puzzle" },
  { title: { en: "OvO" }, img: "ovo", url: "/ovo/", genre: "platformer" },
  { title: { en: "OvO 2" }, img: "ovo-2", url: "/ovo2.html", genre: "platformer", pc: true },
  { title: { en: "OvO Dimensions" }, img: "ovo-dimensions", url: "/ovo-dimensions.html", genre: "platformer" },
  { title: { en: "Paper.io 2" }, img: "paper-io-2", url: "/paperio2/", genre: "survival" },
  { title: { en: "Penalty Kick Online" }, img: "penalty-kick-online", url: "/penkick/", genre: "sports" },
  { title: { en: "Plants vs Zombies" }, img: "pvz", url: "/pvz/", genre: "action" },
  { title: { en: "Ragdoll Archers" }, img: "ragdoll-archers", url: "/ragdoll-archers/", genre: "action" },
  { title: { en: "Ragdoll Hit" }, img: "ragdoll-hit", url: "/ragdoll-hit/", genre: "action", popular: true },
  { title: { en: "Recoil" }, img: "recoil", url: "/recoil.html", genre: "action" },
  { title: { en: "Rise Higher" }, img: "rise-up", url: "/rise-higher/", genre: "survival" },
  { title: { en: "Rocket Goal" }, img: "rocket-goal", url: "/rocketgoal/", genre: "sports", broken: true, leaving: true },
  { title: { en: "Roll" }, img: "roll", url: "/roll.html", genre: "puzzle" },
  { title: { en: "Roper" }, img: "roper", url: "/roper/", genre: "action" },
  { title: { en: "Sky Race 3D" }, img: "sky-race-3d", url: "/skyrace3d.html", genre: "racing" },
  { title: { en: "Slice Master" }, img: "slice-master", url: "/slice-master/", genre: "puzzle", fixed: true },
  { title: { en: "Small World Cup" }, img: "small-world-cup", url: "/small-world-cup.html", genre: "sports" },
  { title: { en: "Soccer Random" }, img: "soccer-random", url: "/randoms/soccer/", genre: "sports" },
  { title: { en: "Spiral Roll" }, img: "slice-roll", url: "/slice-roll/", genre: "action" },
  { title: { en: "Stack" }, img: "stack", url: "/stack/", genre: "puzzle" },
  { title: { en: "Stealing the Diamond" }, img: "stealing-the-diamond", url: "/stickmin/stealingthediamond/", genre: "puzzle" },
  { title: { en: "Stickman Hook" }, img: "stickman-hook", url: "/stickman-hook.html", genre: "platformer" },
  { title: { en: "Subway Surfers" }, img: "subway-surfers", url: "/subway-surfers/", genre: "platformer" },
  { title: { en: "Survival Race" }, img: "survival-race", url: "/survival-race/", genre: "sports", popular: true },
  { title: { en: "Swoop" }, img: "swoop", url: "/SWOOOP.html", genre: "action" },
  { title: { en: "Tap Goal" }, img: "tap-goal", url: "/tap-goal/", genre: "sports" },
  { title: { en: "There Is No Game" }, img: "there-is-no-game", url: "/there-is-no-game.html", genre: "puzzle" },
  { title: { en: "Thorns and Balloons" }, img: "thorns-and-balloons", url: "/thorns-and-balloons/", genre: "puzzle" },
  { title: { en: "Tiny Fishing" }, img: "tiny-fishing", url: "/tiny-fishing/", genre: "clicker" },
  { title: { en: "Tiny Fishing | Update" }, img: "tiny-fishing-update", url: "/tiny-fishing/update/", genre: "clicker" },
  { title: { en: "Tomb of the Mask" }, img: "tomb-of-the-mask", url: "/totm.html", genre: "action" },
  { title: { en: "Volley Random" }, img: "volley-random", url: "/randoms/volley/", genre: "sports" },
  { title: { en: "Web Retro" }, img: "web-retro", url: "/webretro/", genre: "action" },
  { title: { en: "Wheelie Bike" }, img: "wheelie-bike", url: "/wheelie-bike/", genre: "racing" },
  { title: { en: "Jelly Mario" }, img: "jelly-mario", url: "/jellymario.html", genre: "platformer", untested: true },
  { title: { en: "Five Nights at Winston's" }, img: "fnaw", url: "/FNAW/", genre: "survival", horror: true, untested: true },
];