export const gamesData = [
  { title: { en: "99 Balls" }, img: "ninety-nine-balls.jpg", url: "/ninety-nine-balls/", genre: "puzzle" },
  { title: { en: "Angry Birds" }, img: "angry-birds.jpg", url: "/angrybirds.htm", genre: "action" },
  { title: { en: "Basket Random" }, img: "basket-random.jpg", url: "/randoms/basket/", genre: "sports" },
  { title: { en: "Battle Racing Stars" }, img: "battle-racing-stars.jpg", url: "/battle-racing-stars/", genre: "racing", broken: true },
  { title: { en: "BitLife" }, img: "bitlife.png", url: "/bitlife/", genre: "adventure", popular: true },
  { title: { en: "Block Blast" }, img: "block-blast.webp", url: "/block-blast/", genre: "puzzle" },
  { title: { en: "Bloons Tower Defence 5" }, img: "btd5.webp", url: "/btd5.htm", genre: "action" },
  { title: { en: "Boxing Random" }, img: "boxing-random.jpg", url: "/randoms/boxing/", genre: "sports" },
  { title: { en: "Breaking the Bank" }, img: "breaking-the-bank.jpg", url: "/stickmin/breakingthebank/", genre: "puzzle" },
  { title: { en: "Bridge Race" }, img: "bridge-race.jpg", url: "/bridge-race/", genre: "survival" },
  { title: { en: "Car Drawing Game" }, img: "car-drawing-game.jpg", url: "/car-drawing-game/", genre: "racing" },
  { title: { en: "Cookie Clicker" }, img: "cookie-clicker.png", url: "/cookieclicker/", genre: "clicker", broken: true, issue: '59' },
  { title: { en: "Crazy Crash Landing" }, img: "crazy-crash-landing.jpg", url: "/ccl.htm", genre: "survival" },
  { title: { en: "Crossy Road" }, img: "crossy-road.jpg", url: "/crossy-road.html", genre: "racing" },
  { title: { en: "Cut the Rope" }, img: "cut-the-rope.png", url: "/ctr/", genre: "puzzle" },
  { title: { en: "Cut The Rope: Time Travel" }, img: "cut-the-rope-time-travel.jpg", url: "/time-travel/index.html", genre: "puzzle" },
  { title: { en: "Darts Pro" }, img: "darts-pro.jpg", url: "/dartspro/", genre: "sports" },
  { title: { en: "Doge Miner" }, img: "doge-miner.jpg", url: "/DogeMiner/", genre: "clicker" },
  { title: { en: "Doge Miner 2" }, img: "doge-miner-2.jpg", url: "/doge-miner-2/", genre: "clicker" },
  { title: { en: "Draw Climber" }, img: "draw-climber.webp", url: "/draw-climber/", genre: "puzzle" },
  { title: { en: "Draw the Hill" }, img: "draw-the-hill.jpg", url: "/draw-the-hill/", genre: "puzzle" },
  { title: { en: "Drift Boss" }, img: "drift-boss.webp", url: "/drift-boss/", genre: "racing" },
  { title: { en: "Drive Mad" }, img: "drive-mad.webp", url: "/drive-mad/", genre: "racing", popular: true },
  { title: { en: "Driven Wild" }, img: "driven-wild.jpg", url: "/drivenwild/index.html", genre: "racing" },
  { title: { en: "Duck Duck Clicker" }, img: "duck-duck-clicker.webp", url: "/duck-duck-clicker/", genre: "clicker" },
  { title: { en: "Escaping the Prison" }, img: "escaping-the-prison.png", url: "/stickmin/escapingtheprison/", genre: "puzzle" },
  { title: { en: "Fast Runner" }, img: "fast-runner.webp", url: "/fast-runner/", genre: "racing" },
  { title: { en: "Five Nights at Epstein's" }, img: "fnae.jpg", url: "/fnae.html", genre: "survival", horror: true },
  { title: { en: "Five Nights at Freddy's 1" }, img: "fnaf-1.webp", url: "/fnaf/FNAF1/", genre: "survival", horror: true },
  { title: { en: "Five Nights at Freddy's 2" }, img: "fnaf-2.webp", url: "/fnaf/FNAF2/", genre: "survival", horror: true, broken: true },
  { title: { en: "Five Nights at Freddy's 3" }, img: "fnaf-3.webp", url: "/fnaf/FNAF3/", genre: "survival", horror: true },
  { title: { en: "Flappy Bird" }, img: "flappy-bird.jpg", url: "/flappy-bird/", genre: "survival" },
  { title: { en: "Fleeing the Complex" }, img: "fleeing-the-complex.jpg", url: "/stickmin/fleeingthecomplex/", genre: "puzzle" },
  { title: { en: "Formula Rush" }, img: "formula-rush.jpg", url: "/formula-rush/", genre: "racing" },
  { title: { en: "Fruit Ninja" }, img: "fruit-ninja.jpg", url: "/fruitninja.htm", genre: "puzzle" },
  { title: { en: "Geometry Dash SubZero" }, img: "gd-subzero.jpg", url: "/gd-sub0.htm", genre: "survival" },
  { title: { en: "Geometry Dash Wave" }, img: "gd-wave.jpg", url: "/gd-wave/", genre: "survival" },
  { title: { en: "Geometry Dash World" }, img: "gd-world.jpg", url: "/gdworld.htm", genre: "survival" },
  { title: { en: "Gobble" }, img: "gobble.jpg", url: "/gobble/", genre: "action" },
  { title: { en: "Google Games Baseball" }, img: "gg-baseball.webp", url: "/baseball/", genre: "sports" },
  { title: { en: "Google Games Cricket" }, img: "gg-cricket.webp", url: "/cricket17/", genre: "sports" },
  { title: { en: "GunSpin" }, img: "gunspin.webp", url: "/gunspin/", genre: "action", popular: true },
  { title: { en: "Happy Glass" }, img: "happy-glass.png", url: "/happyglass/", genre: "puzzle" },
  { title: { en: "Hundred Percent Golf" }, img: "hundred-percent-golf.png", url: "/hundred-percent-golf/index.html", genre: "sports", broken: true },
  { title: { en: "Idle Football Manager" }, img: "idle-football-manager.webp", url: "/idle-football/", genre: "sports" },
  { title: { en: "Impossible Quiz" }, img: "impossible-quiz.jpg", url: "/impossiblequiz/", genre: "puzzle" },
  { title: { en: "Infiltrating the Airship" }, img: "infiltrating-the-airship.jpg", url: "/stickmin/infiltratingtheairship/", genre: "puzzle" },
  { title: { en: "Jetpack Joyride" }, img: "jetpack-joyride.jpg", url: "/jetpack-joyride/", genre: "action" },
  { title: { en: "Knife Hit" }, img: "knife-hit.png", url: "/knifehit/", genre: "puzzle" },
  { title: { en: "Liquid Sort" }, img: "liquid-sort.jpg", url: "/liquid-sort/", genre: "puzzle" },
  { title: { en: "Monkey Mart" }, img: "monkey-mart.webp", url: "/monkey-mart.html", genre: "adventure" },
  { title: { en: "Monster Tracks" }, img: "monster-tracks.jpg", url: "/monster-tracks.html", genre: "racing" },
  { title: { en: "Moto X3M" }, img: "moto-x3m.jpg", url: "/moto-x3m.html", genre: "racing" },
  { title: { en: "Moto X3M Winter" }, img: "moto-x3m-winter.webp", url: "/x3m/", genre: "racing" },
  { title: { en: "No Pain, No Gain" }, img: "no-pain-no-gain.jpg", url: "/npng/", genre: "action", popular: true },
  { title: { en: "Nut Sort" }, img: "nut-sort.png", url: "/nutsort/", genre: "puzzle" },
  { title: { en: "OvO" }, img: "ovo.webp", url: "/ovo/", genre: "platformer" },
  { title: { en: "OvO 2" }, img: "ovo-2.jpg", url: "/ovo2.html", genre: "platformer", pc: true },
  { title: { en: "OvO Dimensions" }, img: "ovo-dimensions.jpg", url: "/ovo-dimensions.html", genre: "platformer" },
  { title: { en: "Paper.io 2" }, img: "paper-io-2.jpg", url: "/paperio2/", genre: "survival" },
  { title: { en: "Penalty Kick Online" }, img: "penalty-kick-online.jpg", url: "/penkick/", genre: "sports" },
  { title: { en: "Plants vs Zombies" }, img: "pvz.webp", url: "/pvz/", genre: "action" },
  { title: { en: "Ragdoll Archers" }, img: "ragdoll-archers.webp", url: "/ragdoll-archers/", genre: "action" },
  { title: { en: "Ragdoll Hit" }, img: "ragdoll-hit.webp", url: "/ragdoll-hit/", genre: "action", popular: true },
  { title: { en: "Recoil" }, img: "recoil.jpg", url: "/recoil.html", genre: "action" },
  { title: { en: "Rise Higher" }, img: "rise-up.jpg", url: "/rise-higher/", genre: "survival" },
  { title: { en: "Rocket Goal" }, img: "rocket-goal.jpg", url: "/rocketgoal/", genre: "sports", broken: true },
  { title: { en: "Roll" }, img: "roll.jpg", url: "/roll.html", genre: "puzzle" },
  { title: { en: "Roper" }, img: "roper.png", url: "/roper/", genre: "action" },
  { title: { en: "Sky Race 3D" }, img: "sky-race-3d.jpg", url: "/skyrace3d.html", genre: "racing" },
  { title: { en: "Slice Master" }, img: "slice-master.webp", url: "https://game-hub.nyc3.cdn.digitaloceanspaces.com/slice-master/index.html", genre: "puzzle", broken: true, issue: '60' },
  { title: { en: "Small World Cup" }, img: "small-world-cup.jpg", url: "/small-world-cup.html", genre: "sports" },
  { title: { en: "Soccer Random" }, img: "soccer-random.jpg", url: "/randoms/soccer/", genre: "sports" },
  { title: { en: "Spiral Roll" }, img: "slice-roll.webp", url: "/slice-roll/", genre: "action" },
  { title: { en: "Stack" }, img: "stack.jpg", url: "/stack/", genre: "puzzle" },
  { title: { en: "Stealing the Diamond" }, img: "stealing-the-diamond.jpg", url: "/stickmin/stealingthediamond/", genre: "puzzle" },
  { title: { en: "Stickman Hook" }, img: "stickman-hook.jpg", url: "/stickman-hook.html", genre: "platformer" },
  { title: { en: "Subway Surfers" }, img: "subway-surfers.webp", url: "/subway-surfers/", genre: "platformer" },
  { title: { en: "Survival Race" }, img: "survival-race.webp", url: "/survival-race/", genre: "sports", popular: true },
  { title: { en: "Swoop" }, img: "swoop.jpg", url: "/SWOOOP.html", genre: "action" },
  { title: { en: "Tap Goal" }, img: "tap-goal.webp", url: "/tap-goal/", genre: "sports" },
  { title: { en: "There Is No Game" }, img: "there-is-no-game.jpg", url: "/there-is-no-game.html", genre: "puzzle" },
  { title: { en: "Thorns and Balloons" }, img: "thorns-and-balloons.webp", url: "/thorns-and-balloons/", genre: "puzzle" },
  { title: { en: "Tiny Fishing" }, img: "tiny-fishing.webp", url: "/tiny-fishing/", genre: "clicker" },
  { title: { en: "Tiny Fishing | Update" }, img: "tiny-fishing-update.jpg", url: "/tiny-fishing/update/", genre: "clicker" },
  { title: { en: "Tomb of the Mask" }, img: "tomb-of-the-mask.png", url: "/totm.html", genre: "action" },
  { title: { en: "Volley Random" }, img: "volley-random.png", url: "/randoms/volley/", genre: "sports" },
  { title: { en: "Web Retro" }, img: "web-retro.png", url: "/webretro/", genre: "action" },
  { title: { en: "Wheelie Bike" }, img: "wheelie-bike.webp", url: "/wheelie-bike/", genre: "racing" },
];