// This file statically imports all game icon images so they can be bundled correctly.
// A static object is used to map a game's name to its image path.

// NOTE: You will need to replace this placeholder with your actual assets.
export const gameIcons = {
  '0': require('./game-icons/0.jpg'),
  '1': require('./game-icons/1.jpg'),
  '2': require('./game-icons/2.jpg'),
  '3': require('./game-icons/3.jpg'),
  '4': require('./game-icons/4.png'),
  '5': require('./game-icons/5.png'),
  '6': require('./game-icons/6.jpg'),
  '7': require('./game-icons/7.jpg'),
  '8': require('./game-icons/8.jpg'),
  '9': require('./game-icons/9.jpg'),
  'a': require('./game-icons/a.png'),
  'b': require('./game-icons/b.jpg'),
  'c': require('./game-icons/c.png'),
  'd': require('./game-icons/d.jpg'),
  'e': require('./game-icons/e.jpg'),
  'f': require('./game-icons/f.jpg'),
  'g': require('./game-icons/g.jpg'),
  'h': require('./game-icons/h.jpg'),
  'k': require('./game-icons/k.png'),
  'j': require('./game-icons/j.jpg'),
  'i': require('./game-icons/i.png'),
  'l': require('./game-icons/l.webp'),
  'm': require('./game-icons/m.jpg'),
  'n': require('./game-icons/n.jpg'),
  'o': require('./game-icons/o.png'),
  'p': require('./game-icons/p.png'),
  'q': require('./game-icons/q.jpg'),
  'r': require('./game-icons/r.jpg'),
  's': require('./game-icons/s.jpg'),
  't': require('./game-icons/t.png'),
  'u': require('./game-icons/u.jpg'),
  'v': require('./game-icons/v.png'),
  'w': require('./game-icons/w.jpg'),
  'x': require('./game-icons/x.avif'),
  'y': require('./game-icons/y.png'),
  'z': require('./game-icons/z.png'),
  '00': require('./game-icons/00.png'),
  '01' : require('./game-icons/01.jpg'),
  '02': require('./game-icons/02.avif'),
  '25': require('./game-icons/25.png'),
  '12': require('./game-icons/12.jpg'),
  '30': require('./game-icons/30.png'),
  '340': require('./game-icons/340.png'),
  '03': require('./game-icons/03.webp'),
  '67': require('./game-icons/67.png'),
};
