export const gamesData = [
  { title: { en: "Small World Cup" }, img: "ag", url: "/small-world-cup.html", popular: true },
  { title: { en: "Basket Random" }, img: "ac", url: "/randoms/basket/" },
  { title: { en: "BitLife" }, img: "6", url: "/bitlife/" },
  { title: { en: "Block Blast" }, img: "aa", url: "/block-blast/" },
  { title: { en: "Bloons Tower Defence 5" }, img: "m", url: "/btd5.htm" },
  { title: { en: "Boxing Random" }, img: "ab", url: "/randoms/boxing/" },
  { title: { en: "Crazy Crash Landing" }, img: "n", url: "/ccl.htm", popular: true },
  { title: { en: "Darts Pro" }, img: "f", url: "/dartspro/" },
  { title: { en: "Draw Climber" }, img: "g", url: "/draw-climber/" },
  { title: { en: "Drive Mad" }, img: "9", url: "/drive-mad/", popular: true },
  { title: { en: "Duck Duck Clicker" }, img: "4", url: "/duck-duck-clicker/" },
  { title: { en: "Fast Runner" }, img: "t", url: "/fast-runner/" },
  { title: { en: "Flappy Bird" }, img: "h", url: "/flappy-bird/" },

  { title: { en: "Five Nights at Freddy’s 1" }, img: "a", url: "/fnaf/FNAF1/", horror: true },
  { title: { en: "Five Nights at Freddy’s 2" }, img: "ah", url: "/fnaf/FNAF2/", horror: true },
  { title: { en: "Five Nights at Freddy’s 3" }, img: "ai", url: "/fnaf/FNAF3/", horror: true },
  { title: { en: "Five Nights at Epstein’s" }, img: "br", url: "/fnae.html", horror: true },

  { title: { en: "Geometry Dash Wave" }, img: "x", url: "/gd-wave/" },
  { title: { en: "Gobble" }, img: "r", url: "/gobble/" },
  { title: { en: "Google Games Baseball" }, img: "y", url: "/baseball/" },
  { title: { en: "Google Games Cricket" }, img: "z", url: "/cricket17/" },
  { title: { en: "GunSpin" }, img: "8", url: "/gunspin/", popular: true },

  { title: { en: "Idle Football Manager" }, img: "k", url: "/idle-football/" },
  { title: { en: "Happy Glass" }, img: "an", url: "/happyglass/" },
  { title: { en: "NEW Tiny Fishing" }, img: "aq", url: "/tiny-fishing/update", broken: true },
  { title: { en: "Nut Sort" }, img: "aj", url: "/nutsort/" },
  { title: { en: "OvO" }, img: "7", url: "/ovo/" },
  { title: { en: "Paper.io 2" }, img: "am", url: "/paperio2/" },

  { title: { en: "Penalty Kick Online" }, img: "e", url: "/penkick/" },
  { title: { en: "Plants vs Zombies" }, img: "p", url: "/pvz/" },
  { title: { en: "Ragdoll Archers" }, img: "2", url: "/ragdoll-archers/" },
  { title: { en: "Ragdoll Hit" }, img: "c", url: "/ragdoll-hit/" },

  { title: { en: "Roll" }, img: "w", url: "/roll.html" },
  { title: { en: "Roper" }, img: "b", url: "/roper/" },
  { title: { en: "Slice Master" }, img: "q", url: "https://game-hub.nyc3.cdn.digitaloceanspaces.com/slice-master/index.html", broken: true },

  { title: { en: "Soccer Random" }, img: "ak", url: "/randoms/soccer/" },
  { title: { en: "Spiral Roll" }, img: "i", url: "/slice-roll/" },
  { title: { en: "Subway Surfers" }, img: "3", url: "/subway-surfers/" },

  { title: { en: "Survival Race" }, img: "d", url: "/survival-race/" },
  { title: { en: "Tap Goal" }, img: "s", url: "/tap-goal/" },
  { title: { en: "There Is No Game" }, img: "af", url: "/there-is-no-game.html" },
  { title: { en: "Thorns and Balloons" }, img: "5", url: "/thorns-and-balloons/", popular: true },

  { title: { en: "Tiny Fishing" }, img: "1", url: "/tiny-fishing/" },
  { title: { en: "Volley Random" }, img: "al", url: "/randoms/volley/" },
  { title: { en: "Wheelie Bike" }, img: "l", url: "/wheelie-bike/" },
  { title: { en: "Moto X3M Winter" }, img: "0", url: "/x3m/" },

  { title: { en: "Drift Boss" }, img: "u", url: "/drift-boss/" },

  { title: { en: "Stealing the Diamond" }, img: "at", url: "/stickmin/stealingthediamond/" },
  { title: { en: "Escaping the Prison" }, img: "ar", url: "/stickmin/escapingtheprison/" },
  { title: { en: "Fleeing the Complex" }, img: "as", url: "/stickmin/fleeingthecomplex/" },
  { title: { en: "Infiltrating the Airship" }, img: "au", url: "/stickmin/infiltratingtheairship/" },

  { title: { en: "Swoop" }, img: "ap", url: "/SWOOOP.html" },
  { title: { en: "Jetpack Joyride" }, img: "aw", url: "/jetpack-joyride/", popular: true },
  { title: { en: "Cut the Rope" }, img: "ay", url: "/ctr/" },
  { title: { en: "Stickman Hook" }, img: "ax", url: "/stickman-hook.html", popular: true },

  { title: { en: "Breaking the Bank" }, img: "az", url: "/stickmin/breakingthebank/" },
  { title: { en: "Crossy Road" }, img: "ba", url: "/crossy-road.html" },
  { title: { en: "Monkey Mart" }, img: "bb", url: "/monkey-mart.html", popular: true },
  { title: { en: "Draw the Hill" }, img: "bc", url: "/draw-the-hill/" },

  { title: { en: "OvO Dimensions" }, img: "be", url: "/ovo-dimensions.html" },
  { title: { en: "Recoil" }, img: "bf", url: "/recoil.html" },
  { title: { en: "OvO 2" }, img: "bh", url: "/ovo2.html", pc: true },

  { title: { en: "Fruit Ninja" }, img: "v", url: "/fruitninja.htm" },
  { title: { en: "GD SubZero" }, img: "j", url: "/gd-sub0.htm"},
  { title: { en: "GD World" }, img: "av", url: "/gdworld.htm"},
  { title: { en: "Driven Wild" }, img: "ao", url: "/drivenwild/index.html" },
  { title: { en: "Knife Hit" }, img: "bg", url: "/knifehit/" },
  { title: { en: "Car Drawing Game" }, img: "ad", url: "/car-drawing-game/" },
  { title: { en: "Monster Tracks" }, img: "o", url: "/monster-tracks.html" },

  { title: { en: "Doge Miner" }, img: "bi", url: "/DogeMiner/" },
  { title: { en: "Impossible Quiz" }, img: "bj", url: "/impossiblequiz/" },
  { title: { en: "Sky Race 3D" }, img: "bk", url: "/skyrace3d.html" },

  { title: { en: "Moto X3M" }, img: "bl", url: "/moto-x3m.html" },
  { title: { en: "GD Lite" }, img: "bn", url: "/gdlite/" },
  { title: { en: "Cookie Clicker" }, img: "bo", url: "/cookieclicker/", broken: true },
  { title: { en: "Bridge Race" }, img: "bp", url: "/bridge-race/" },
  { title: { en: "Doge Miner 2" }, img: "bd", url: "/doge-miner-2/" },

  { title: { en: "Tomb of the Mask" }, img: "ae", url: "/totm.html" },
  { title: { en: "Rocket Goal" }, img: "bq", url: "/rocketgoal/" },
  { title: { en: "Angry Birds" }, img: "bs", url: "/angrybirds.htm" },
  { title: { en: "Cut The Rope: Time Travel" }, img: "bt", url: "/time-travel/index.html" },
];